const EVENTS = new Map();

const NUMBERS = [
    {
        number: 0,
        red: null,
        odd: null,
        big: null,
        dozen: null,
        zeroGame: true,
        voisins: true,
        orphelins: false,
        tier: false,
        sector: 'zero',
        neighbors_1: [26, 32],
        neighbors_2: [3, 26, 32, 15],
        neighbors_3: [35, 3, 26, 32, 15, 19]
    }, {
        number: 32,
        red: true,
        odd: false,
        big: true,
        dozen: 3,
        zeroGame: true,
        voisins: true,
        orphelins: false,
        tier: false,
        sector: 'top-right',
        neighbors_1: [0, 15],
        neighbors_2: [26, 0, 15, 19],
        neighbors_3: [3, 26, 0, 15, 19, 4]
    }, {
        number: 15,
        red: false,
        odd: true,
        big: false,
        dozen: 2,
        zeroGame: true,
        voisins: true,
        orphelins: false,
        tier: false,
        sector: 'top-right',
        neighbors_1: [32, 19],
        neighbors_2: [0, 32, 19, 4],
        neighbors_3: [26, 0, 32, 19, 4, 21]
    }, {
        number: 19,
        red: true,
        odd: true,
        big: true,
        dozen: 2,
        zeroGame: false,
        voisins: true,
        orphelins: false,
        tier: false,
        sector: 'top-right',
        neighbors_1: [15, 4],
        neighbors_2: [32, 15, 4, 21],
        neighbors_3: [0, 32, 15, 4, 21, 2]
    }, {
        number: 4,
        red: false,
        odd: false,
        big: false,
        dozen: 1,
        zeroGame: false,
        voisins: true,
        orphelins: false,
        tier: false,
        sector: 'top-right',
        neighbors_1: [19, 21],
        neighbors_2: [15, 19, 21, 2],
        neighbors_3: [32, 15, 19, 21, 2, 25]
    }, {
        number: 21,
        red: true,
        odd: true,
        big: true,
        dozen: 2,
        zeroGame: false,
        voisins: true,
        orphelins: false,
        tier: false,
        sector: 'top-right',
        neighbors_1: [4, 2],
        neighbors_2: [19, 4, 2, 25],
        neighbors_3: [15, 19, 4, 2, 25, 17]
    }, {
        number: 2,
        red: false,
        odd: false,
        big: false,
        dozen: 1,
        zeroGame: false,
        voisins: true,
        orphelins: false,
        tier: false,
        sector: 'top-right',
        neighbors_1: [21, 25],
        neighbors_2: [4, 21, 25, 17],
        neighbors_3: [19, 4, 21, 25, 17, 34]
    }, {
        number: 25,
        red: true,
        odd: true,
        big: true,
        dozen: 3,
        zeroGame: false,
        voisins: true,
        orphelins: false,
        tier: false,
        sector: 'top-right',
        neighbors_1: [2, 17],
        neighbors_2: [21, 2, 17, 34],
        neighbors_3: [4, 21, 2, 17, 34, 6]
    }, {
        number: 17,
        red: false,
        odd: true,
        big: false,
        dozen: 2,
        zeroGame: false,
        voisins: false,
        orphelins: true,
        tier: false,
        sector: 'top-right',
        neighbors_1: [25, 34],
        neighbors_2: [2, 25, 34, 6],
        neighbors_3: [21, 2, 25, 34, 6, 27]
    }, {
        number: 34,
        red: true,
        odd: false,
        big: true,
        dozen: 3,
        zeroGame: false,
        voisins: false,
        orphelins: true,
        tier: false,
        sector: 'top-right',
        neighbors_1: [17, 6],
        neighbors_2: [25, 17, 6, 27],
        neighbors_3: [2, 25, 17, 6, 27, 13]
    }, {
        number: 6,
        red: false,
        odd: false,
        big: false,
        dozen: 1,
        zeroGame: false,
        voisins: false,
        orphelins: true,
        tier: false,
        sector: 'bottom-right',
        neighbors_1: [34, 27],
        neighbors_2: [17, 34, 27, 13],
        neighbors_3: [25, 17, 34, 27, 13, 36]
    }, {
        number: 27,
        red: true,
        odd: true,
        big: true,
        dozen: 3,
        zeroGame: false,
        voisins: false,
        orphelins: false,
        tier: true,
        sector: 'bottom-right',
        neighbors_1: [6, 13],
        neighbors_2: [34, 6, 13, 36],
        neighbors_3: [17, 34, 6, 13, 36, 11]
    }, {
        number: 13,
        red: false,
        odd: true,
        big: false,
        dozen: 2,
        zeroGame: false,
        voisins: false,
        orphelins: false,
        tier: true,
        sector: 'bottom-right',
        neighbors_1: [27, 36],
        neighbors_2: [6, 27, 36, 11],
        neighbors_3: [34, 6, 27, 36, 11, 30]
    }, {
        number: 36,
        red: true,
        odd: false,
        big: true,
        dozen: 3,
        zeroGame: false,
        voisins: false,
        orphelins: false,
        tier: true,
        sector: 'bottom-right',
        neighbors_1: [13, 11],
        neighbors_2: [27, 13, 11, 30],
        neighbors_3: [6, 27, 13, 11, 30, 8]
    }, {
        number: 11,
        red: false,
        odd: true,
        big: false,
        dozen: 1,
        zeroGame: false,
        voisins: false,
        orphelins: false,
        tier: true,
        sector: 'bottom-right',
        neighbors_1: [36, 30],
        neighbors_2: [13, 36, 30, 8],
        neighbors_3: [27, 13, 36, 30, 8, 23]
    }, {
        number: 30,
        red: true,
        odd: false,
        big: true,
        dozen: 3,
        zeroGame: false,
        voisins: false,
        orphelins: false,
        tier: true,
        sector: 'bottom-right',
        neighbors_1: [11, 8],
        neighbors_2: [36, 11, 8, 23],
        neighbors_3: [13, 36, 11, 8, 23, 10]
    }, {
        number: 8,
        red: false,
        odd: false,
        big: false,
        dozen: 1,
        zeroGame: false,
        voisins: false,
        orphelins: false,
        tier: true,
        sector: 'bottom-right',
        neighbors_1: [30, 23],
        neighbors_2: [11, 30, 23, 10],
        neighbors_3: [36, 11, 30, 23, 10, 5]
    }, {
        number: 23,
        red: true,
        odd: true,
        big: true,
        dozen: 2,
        zeroGame: false,
        voisins: false,
        orphelins: false,
        tier: true,
        sector: 'bottom-right',
        neighbors_1: [8, 10],
        neighbors_2: [30, 8, 10, 5],
        neighbors_3: [11, 30, 8, 10, 5, 24]
    }, {
        number: 10,
        red: false,
        odd: false,
        big: false,
        dozen: 1,
        zeroGame: false,
        voisins: false,
        orphelins: false,
        tier: true,
        sector: 'bottom-right',
        neighbors_1: [23, 5],
        neighbors_2: [8, 23, 5, 24],
        neighbors_3: [30, 8, 23, 5, 24, 16]
    }, {
        number: 5,
        red: true,
        odd: true,
        big: false,
        dozen: 1,
        zeroGame: false,
        voisins: false,
        orphelins: false,
        tier: true,
        sector: 'bottom-left',
        neighbors_1: [10, 24],
        neighbors_2: [23, 10, 24, 16],
        neighbors_3: [8, 23, 10, 24, 16, 33]
    }, {
        number: 24,
        red: false,
        odd: false,
        big: true,
        dozen: 2,
        zeroGame: false,
        voisins: false,
        orphelins: false,
        tier: true,
        sector: 'bottom-left',
        neighbors_1: [5, 16],
        neighbors_2: [10, 5, 16, 33],
        neighbors_3: [23, 10, 5, 16, 33, 1]
    }, {
        number: 16,
        red: true,
        odd: false,
        big: false,
        dozen: 2,
        zeroGame: false,
        voisins: false,
        orphelins: false,
        tier: true,
        sector: 'bottom-left',
        neighbors_1: [24, 33],
        neighbors_2: [5, 25, 33, 1],
        neighbors_3: [10, 5, 25, 33, 1, 20]
    }, {
        number: 33,
        red: false,
        odd: true,
        big: true,
        dozen: 3,
        zeroGame: false,
        voisins: false,
        orphelins: false,
        tier: true,
        sector: 'bottom-left',
        neighbors_1: [16, 1],
        neighbors_2: [24, 16, 1, 20],
        neighbors_3: [5, 24, 16, 1, 20, 14]
    }, {
        number: 1,
        red: true,
        odd: true,
        big: false,
        dozen: 1,
        zeroGame: false,
        voisins: false,
        orphelins: true,
        tier: false,
        sector: 'bottom-left',
        neighbors_1: [33, 20],
        neighbors_2: [16, 33, 20, 14],
        neighbors_3: [24, 16, 33, 20, 14, 31]
    }, {
        number: 20,
        red: false,
        odd: false,
        big: true,
        dozen: 2,
        zeroGame: false,
        voisins: false,
        orphelins: true,
        tier: false,
        sector: 'bottom-left',
        neighbors_1: [1, 14],
        neighbors_2: [33, 1, 14, 31],
        neighbors_3: [16, 33, 1, 14, 31, 9]
    }, {
        number: 14,
        red: true,
        odd: false,
        big: false,
        dozen: 2,
        zeroGame: false,
        voisins: false,
        orphelins: true,
        tier: false,
        sector: 'bottom-left',
        neighbors_1: [20, 31],
        neighbors_2: [1, 20, 31, 9],
        neighbors_3: [33, 1, 20, 31, 9, 22]
    }, {
        number: 31,
        red: false,
        odd: true,
        big: true,
        dozen: 3,
        zeroGame: false,
        voisins: false,
        orphelins: true,
        tier: false,
        sector: 'bottom-left',
        neighbors_1: [14, 9],
        neighbors_2: [20, 14, 9, 22],
        neighbors_3: [1, 20, 14, 9, 22, 18]
    }, {
        number: 9,
        red: true,
        odd: true,
        big: false,
        dozen: 1,
        zeroGame: false,
        voisins: false,
        orphelins: true,
        tier: false,
        sector: 'bottom-left',
        neighbors_1: [31, 22],
        neighbors_2: [14, 31, 22, 18],
        neighbors_3: [20, 14, 31, 22, 18, 29]
    }, {
        number: 22,
        red: false,
        odd: false,
        big: true,
        dozen: 2,
        zeroGame: false,
        voisins: true,
        orphelins: false,
        tier: false,
        sector: 'top-left',
        neighbors_1: [9, 18],
        neighbors_2: [31, 9, 18, 29],
        neighbors_3: [14, 31, 9, 18, 29, 7]
    }, {
        number: 18,
        red: true,
        odd: false,
        big: false,
        dozen: 2,
        zeroGame: false,
        voisins: true,
        orphelins: false,
        tier: false,
        sector: 'top-left',
        neighbors_1: [22, 29],
        neighbors_2: [9, 22, 29, 7],
        neighbors_3: [31, 9, 22, 29, 7, 28]
    }, {
        number: 29,
        red: false,
        odd: true,
        big: true,
        dozen: 3,
        zeroGame: false,
        voisins: true,
        orphelins: false,
        tier: false,
        sector: 'top-left',
        neighbors_1: [18, 7],
        neighbors_2: [22, 18, 7, 28],
        neighbors_3: [9, 22, 18, 7, 28, 12]
    }, {
        number: 7,
        red: true,
        odd: true,
        big: false,
        dozen: 1,
        zeroGame: false,
        voisins: true,
        orphelins: false,
        tier: false,
        sector: 'top-left',
        neighbors_1: [29, 28],
        neighbors_2: [18, 29, 28, 12],
        neighbors_3: [22, 18, 29, 28, 12, 35]
    }, {
        number: 28,
        red: false,
        odd: false,
        big: true,
        dozen: 3,
        zeroGame: false,
        voisins: true,
        orphelins: false,
        tier: false,
        sector: 'top-left',
        neighbors_1: [7, 12],
        neighbors_2: [29, 7, 12, 35],
        neighbors_3: [18, 29, 7, 12, 35, 3]
    }, {
        number: 12,
        red: true,
        odd: false,
        big: false,
        dozen: 1,
        zeroGame: true,
        voisins: true,
        orphelins: false,
        tier: false,
        sector: 'top-left',
        neighbors_1: [28, 35],
        neighbors_2: [7, 28, 35, 3],
        neighbors_3: [29, 7, 28, 35, 3, 26]
    }, {
        number: 35,
        red: false,
        odd: true,
        big: true,
        dozen: 3,
        zeroGame: true,
        voisins: true,
        orphelins: false,
        tier: false,
        sector: 'top-left',
        neighbors_1: [12, 3],
        neighbors_2: [28, 12, 3, 26],
        neighbors_3: [7, 28, 12, 3, 26, 0]
    }, {
        number: 3,
        red: true,
        odd: true,
        big: false,
        dozen: 1,
        zeroGame: true,
        voisins: true,
        orphelins: false,
        tier: false,
        sector: 'top-left',
        neighbors_1: [35, 26],
        neighbors_2: [12, 35, 26, 0],
        neighbors_3: [28, 12, 35, 26, 0, 32]
    }, {
        number: 26,
        red: false,
        odd: false,
        big: true,
        dozen: 3,
        zeroGame: true,
        voisins: true,
        orphelins: false,
        tier: false,
        sector: 'top-left',
        neighbors_1: [3, 0],
        neighbors_2: [35, 3, 0, 32],
        neighbors_3: [12, 35, 3, 0, 32, 15]
    }
];

const NUMBER_INFO = new Map(NUMBERS.map((data) => {
    const { number } = data;
    return [number, data];
}));
